const ConversationConstants = {
  CONVERSATIONS_RECEIVED: "CONVERSATIONS_RECEIVED",
  CONVERSATION_RECEIVED: "CONVERSATION_RECEIVED",
  CONVERSATION_REMOVED: "CONVERSATION_REMOVED"
};
module.exports = ConversationConstants;
