const FilterConstants = {
  UPDATE_LOOKING_FOR: "UPDATE_LOOKING_FOR",
  UPDATE_MAX_AGE: "UPDATE_MAX_AGE",
  UPDATE_MIN_AGE: "UPDATE_MIN_AGE",
  UPDATE_MAX_DISTANCE: "UPDATE_MAX_DISTANCE"
};

module.exports = FilterConstants;
